import './globals.css'
import { Inter } from 'next/font/google'
import TopBar from "@/component/topBar";
import LeftBar from "@/component/leftBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <LeftBar />
        {children}</body>
    </html>
  )
}
